"""billing_rbac_ai_usage

Revision ID: a76aff43b5a8
Revises: f9111df08e5a
Create Date: 2026-01-03 18:43:04.690748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76aff43b5a8'
down_revision: Union[str, Sequence[str], None] = 'f9111df08e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_stripe_customers_user_id'), 'stripe_customers', ['user_id'], unique=True)
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_id', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stripe_sub_user_status', 'stripe_subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_status'), 'stripe_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), 'stripe_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_stripe_subscriptions_user_id'), 'stripe_subscriptions', ['user_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_ledger_action'), 'usage_ledger', ['action'], unique=False)
    op.create_index(op.f('ix_usage_ledger_user_id'), 'usage_ledger', ['user_id'], unique=False)
    op.create_index('ix_usage_user_action_created', 'usage_ledger', ['user_id', 'action', 'created_at', 'id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('constellation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_constellation_id'), 'chat_threads', ['constellation_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_profile_id'), 'chat_threads', ['profile_id'], unique=False)
    op.create_index('ix_chat_threads_user_created', 'chat_threads', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_thread_created', 'chat_messages', ['thread_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', 'clinician', name='userrole'), nullable=False, server_default='user'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_thread_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index('ix_chat_threads_user_created', table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_profile_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_constellation_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index('ix_usage_user_action_created', table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_user_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_action'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_stripe_subscriptions_user_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_status'), table_name='stripe_subscriptions')
    op.drop_index('ix_stripe_sub_user_status', table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_customers_user_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_table('stripe_customers')
    # ### end Alembic commands ###
