"""init

Revision ID: b86c9821ddfb
Revises: 
Create Date: 2026-01-03 14:15:33.679700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86c9821ddfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('constellations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constellations_user_id'), 'constellations', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('person_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkins_profile_created_id', 'checkins', ['profile_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_checkins_profile_id'), 'checkins', ['profile_id'], unique=False)
    op.create_index(op.f('ix_checkins_ts'), 'checkins', ['ts'], unique=False)
    op.create_table('clinical_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_profile_created_id', 'clinical_records', ['profile_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_clinical_records_profile_id'), 'clinical_records', ['profile_id'], unique=False)
    op.create_index(op.f('ix_clinical_records_ts'), 'clinical_records', ['ts'], unique=False)
    op.create_table('constellation_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('constellation_id', sa.String(), nullable=False),
    sa.Column('from_profile_id', sa.String(), nullable=False),
    sa.Column('to_profile_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.ForeignKeyConstraint(['from_profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['to_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constellation_id', 'from_profile_id', 'to_profile_id', 'relationship', name='uq_constellation_edge')
    )
    op.create_index(op.f('ix_constellation_edges_constellation_id'), 'constellation_edges', ['constellation_id'], unique=False)
    op.create_index(op.f('ix_constellation_edges_from_profile_id'), 'constellation_edges', ['from_profile_id'], unique=False)
    op.create_index(op.f('ix_constellation_edges_to_profile_id'), 'constellation_edges', ['to_profile_id'], unique=False)
    op.create_index('ix_edge_constellation_from_to', 'constellation_edges', ['constellation_id', 'from_profile_id', 'to_profile_id'], unique=False)
    op.create_table('constellation_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('constellation_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constellation_id', 'profile_id', name='uq_constellation_member')
    )
    op.create_index(op.f('ix_constellation_members_constellation_id'), 'constellation_members', ['constellation_id'], unique=False)
    op.create_index(op.f('ix_constellation_members_profile_id'), 'constellation_members', ['profile_id'], unique=False)
    op.create_index('ix_member_constellation_profile', 'constellation_members', ['constellation_id', 'profile_id'], unique=False)
    op.create_table('constellation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('constellation_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constellation_runs_as_of'), 'constellation_runs', ['as_of'], unique=False)
    op.create_index(op.f('ix_constellation_runs_constellation_id'), 'constellation_runs', ['constellation_id'], unique=False)
    op.create_index('ix_constellation_runs_created_id', 'constellation_runs', ['constellation_id', 'created_at', 'id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_as_of'), 'readings', ['as_of'], unique=False)
    op.create_index('ix_readings_profile_created_id', 'readings', ['profile_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_readings_profile_id'), 'readings', ['profile_id'], unique=False)
    op.create_table('state_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('w_user', sa.Float(), nullable=False),
    sa.Column('w_timing', sa.Float(), nullable=False),
    sa.Column('w_context', sa.Float(), nullable=False),
    sa.Column('stress_bias', sa.Float(), nullable=False),
    sa.Column('stress_scale', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_models_profile_id'), 'state_models', ['profile_id'], unique=True)
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('scroll_depth', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_profile_id'), 'telemetry_events', ['profile_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_ts'), 'telemetry_events', ['ts'], unique=False)
    op.create_index('ix_telemetry_profile_created_id', 'telemetry_events', ['profile_id', 'created_at', 'id'], unique=False)
    op.create_table('computed_layers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('reading_id', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_layers_as_of'), 'computed_layers', ['as_of'], unique=False)
    op.create_index(op.f('ix_computed_layers_inputs_hash'), 'computed_layers', ['inputs_hash'], unique=False)
    op.create_index(op.f('ix_computed_layers_layer'), 'computed_layers', ['layer'], unique=False)
    op.create_index(op.f('ix_computed_layers_profile_id'), 'computed_layers', ['profile_id'], unique=False)
    op.create_index(op.f('ix_computed_layers_reading_id'), 'computed_layers', ['reading_id'], unique=False)
    op.create_index('ix_layers_profile_layer_created_id', 'computed_layers', ['profile_id', 'layer', 'created_at', 'id'], unique=False)
    op.create_table('constellation_layers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('constellation_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['constellation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constellation_layers_as_of'), 'constellation_layers', ['as_of'], unique=False)
    op.create_index(op.f('ix_constellation_layers_constellation_id'), 'constellation_layers', ['constellation_id'], unique=False)
    op.create_index('ix_constellation_layers_created_id', 'constellation_layers', ['constellation_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_constellation_layers_inputs_hash'), 'constellation_layers', ['inputs_hash'], unique=False)
    op.create_index(op.f('ix_constellation_layers_layer'), 'constellation_layers', ['layer'], unique=False)
    op.create_index('ix_constellation_layers_run_created_id', 'constellation_layers', ['constellation_id', 'run_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_constellation_layers_run_id'), 'constellation_layers', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_constellation_layers_run_id'), table_name='constellation_layers')
    op.drop_index('ix_constellation_layers_run_created_id', table_name='constellation_layers')
    op.drop_index(op.f('ix_constellation_layers_layer'), table_name='constellation_layers')
    op.drop_index(op.f('ix_constellation_layers_inputs_hash'), table_name='constellation_layers')
    op.drop_index('ix_constellation_layers_created_id', table_name='constellation_layers')
    op.drop_index(op.f('ix_constellation_layers_constellation_id'), table_name='constellation_layers')
    op.drop_index(op.f('ix_constellation_layers_as_of'), table_name='constellation_layers')
    op.drop_table('constellation_layers')
    op.drop_index('ix_layers_profile_layer_created_id', table_name='computed_layers')
    op.drop_index(op.f('ix_computed_layers_reading_id'), table_name='computed_layers')
    op.drop_index(op.f('ix_computed_layers_profile_id'), table_name='computed_layers')
    op.drop_index(op.f('ix_computed_layers_layer'), table_name='computed_layers')
    op.drop_index(op.f('ix_computed_layers_inputs_hash'), table_name='computed_layers')
    op.drop_index(op.f('ix_computed_layers_as_of'), table_name='computed_layers')
    op.drop_table('computed_layers')
    op.drop_index('ix_telemetry_profile_created_id', table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_ts'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_profile_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_state_models_profile_id'), table_name='state_models')
    op.drop_table('state_models')
    op.drop_index(op.f('ix_readings_profile_id'), table_name='readings')
    op.drop_index('ix_readings_profile_created_id', table_name='readings')
    op.drop_index(op.f('ix_readings_as_of'), table_name='readings')
    op.drop_table('readings')
    op.drop_index('ix_constellation_runs_created_id', table_name='constellation_runs')
    op.drop_index(op.f('ix_constellation_runs_constellation_id'), table_name='constellation_runs')
    op.drop_index(op.f('ix_constellation_runs_as_of'), table_name='constellation_runs')
    op.drop_table('constellation_runs')
    op.drop_index('ix_member_constellation_profile', table_name='constellation_members')
    op.drop_index(op.f('ix_constellation_members_profile_id'), table_name='constellation_members')
    op.drop_index(op.f('ix_constellation_members_constellation_id'), table_name='constellation_members')
    op.drop_table('constellation_members')
    op.drop_index('ix_edge_constellation_from_to', table_name='constellation_edges')
    op.drop_index(op.f('ix_constellation_edges_to_profile_id'), table_name='constellation_edges')
    op.drop_index(op.f('ix_constellation_edges_from_profile_id'), table_name='constellation_edges')
    op.drop_index(op.f('ix_constellation_edges_constellation_id'), table_name='constellation_edges')
    op.drop_table('constellation_edges')
    op.drop_index(op.f('ix_clinical_records_ts'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_profile_id'), table_name='clinical_records')
    op.drop_index('ix_clinical_profile_created_id', table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_checkins_ts'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_profile_id'), table_name='checkins')
    op.drop_index('ix_checkins_profile_created_id', table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_constellations_user_id'), table_name='constellations')
    op.drop_table('constellations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
